### ISSUE TITLE
Items are not populating on the index.html page

### ISSUE THREAD

**Issue by testingapisname** [KerfuffleV2/tfti#1]
It is probably something that I am doing wrong. I am able to open the index page manually and launch an http server by using the command "py -3 -m http.server" in that same directory but the shop at the top has no items. The screenshot also includes the console logs.
![ConsoleErrors](https://user-images.githubusercontent.com/22276414/61681176-07792400-acd2-11e9-87d7-f0790bf86a56.png)

This is how I have the files set up:
![FileTree](https://user-images.githubusercontent.com/22276414/61680748-6473da80-acd0-11e9-936f-7e9ec214c570.png)

![FileTree2](https://user-images.githubusercontent.com/22276414/61680847-af8ded80-acd0-11e9-9c87-ce3a33901491.png)

![FileTree3](https://user-images.githubusercontent.com/22276414/61680849-b157b100-acd0-11e9-9cc0-c67cab1ca12f.png)

Please let me know if you have any ideas on what I am doing wrong. Thank you!

**Comment by testingapisname** [comment]
Was able to get this working by looking at the red error and realizing that file was not in the right place. Moved it into the js folder and it worked fine.

**Comment by KerfuffleV2** [comment]
@eilersjame15 Glad to hear you figured it out. The way I had the repo set up definitely was not intuitive!
I made some recent improvements to the project structure which should help.
If you use the build script in utils, you should just be able to use the `site` directory as the webserver base directory without having to do any further copying.

**Comment by testingapisname** [comment]
Sweet sounds good. I'm looking at how to add tool tips for the basic items when you hover over them like the buildable items do.

**Comment by KerfuffleV2** [comment]
> Sweet sounds good. I'm looking at how to add tool tips for the basic items when you hover over them like the buildable items do.

@eilersjame15 If you're okay with it being displayed in one of the two existing static tooltip location (**b**uildable, **c**ombinations) then you'd need to:

1. Modify the `Ti.tip` function to be able to be passed a single character, detect this with `len(c)` or whatever and lookup the base item instead of full item in that case.
2. Modify `Ti.mkbuttons` to add `onmouseover` and `onmouseout` attributes for the image basically like the method above it (`Ti.rendercomponentstr`).
3. You'd probably also want to modify the component names to include more useful information like Bow giving +20 attack since a tooltip that just shows "sword" probably isn't super useful.

The components do currently have a normal tooltip via the `title` attribute. I _probably_ won't add display in the static on page tooltip positions myself for the base components since it doesn't seem intuitive to have them show up in the Buildable or Combinations areas and I don't really want to allocate more areas in the page for tooltips since it uses up space always. Eventually I plan to improve how tooltips are displayed.

**Comment by KerfuffleV2** [comment]
@eilersjame15 Okay, so ignore what I said in the post above.

I bit the bullet and revamped the tooltip system so none of what I said before applies anymore. Hopefully it's an improvement!
