### ISSUE TITLE
[Feature request] need an new better UI for floating window

### ISSUE THREAD

**Issue by LazyZhu** [KerfuffleV2/tfti#2]
tfti is wonderful tool for tft beginners, it's even better to work with [Pennywise](https://github.com/kamranahmedse/pennywise), but right now tfti not designed for small windows.

Edit:
Personally modified:
![20190731000820](https://user-images.githubusercontent.com/2244967/62146264-9962db80-b327-11e9-8f93-d62e286be940.png)

**Comment by KerfuffleV2** [comment]
@LazyZhu Thanks for the comment. 

It's a little hard to see exactly what the problem is due to the low opacity of the TFTI window. I couldn't reproduce that result from the cheatsheet part with either Chrome or Firefox even with a low window size.

It's not really intended to have all the sections enabled on a small screen. I don't see a practical way to fit all the information in a small space. The best I could do is provide another even smaller icon size and possibly reduce font sizes if the screen is small, but that could make it quite hard to sort through the information and you'd likely still need to disable some sections to fit it all in the window.

Was your main issue the cheatsheet section?

**Comment by LazyZhu** [comment]
Above is a tfti.css modified version, which i reduce icon size and reduce font size like you said. I also removed gap/pad size(they actually took lots of space).

Can we add special design for this?

**Comment by KerfuffleV2** [comment]
@LazyZhu Ah, it's a modified version. I will look into making it more compact, at least when the screen size is low and and another even smaller icon option.

**Comment by LazyZhu** [comment]
Looking froward for this, thanks to your work. 

Also TFT [patch](https://euw.leagueoflegends.com/en/news/game-updates/patch/teamfight-tactics-patch-915-notes) 9.15 released, here are items related changes:
~~~
Locket gives a 200 HP Shield ⇒ Locket gives a 250 HP Shield that lasts for 4 seconds.
Ionic Spark Damage: 200 ⇒ 150
Hush Silence Duration: 5 seconds ⇒ 3 seconds
Statikk Shiv Damage: 100 ⇒ 90
~~~

**Comment by KerfuffleV2** [comment]
@LazyZhu I've made some improvements for the interface to be more compact. Paddings and font scale are also now based on the icon scale. I've added a "Tiny" icon scale you can select also. It also won't use the double column Have/Want scheme if the screen size is lower than 600. Please let me know if this solves your issue.

(Also updated the icon text yesterday, rating adjustments based on the new meta still to be done.)

**Comment by LazyZhu** [comment]
Yes, it's much better now, but a small issue in tiny mode here:
![20190801204548](https://user-images.githubusercontent.com/2244967/62294638-faacbb00-b49d-11e9-9921-b7241c2a8afe.png)
The two base items are not on the same height of combined item.

**Comment by KerfuffleV2** [comment]
@LazyZhu Should be fixed now, although I'm not sure why it needed the change. Grid layout should have constrained the icons to be in line with with the rest.

**Comment by LazyZhu** [comment]
Thank you. 
It works as intend now.

**Comment by KerfuffleV2** [comment]
> Thank you. It works as intend now.

No problem. Thanks again for the feedback and helping me to improve the tool!
